# Usar Node.js compatible
FROM node:22-alpine  AS builder

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar los archivos de configuración de dependencias
COPY . .
COPY package/v22/package.json ./

# Instalar Angular CLI y dependencias
RUN rm -f package-lock.json && npm add --global nx && npm install

# Construye la librería de Angular (ajusta el nombre de tu librería)
RUN npm run docker-build

# --- Extrae el resultado ---
FROM alpine:latest AS output

# Copia los archivos construidos desde la etapa anterior
COPY --from=builder /app/dist/ui-angular /ds-ng
