name: Publish Multi-version Bamboo

on:
  push:
    branches:
      - develop

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        angular-version: [17, 18, 19, 20]
        include:
          - angular-version: 17
            node-version: 18
          - angular-version: 18
            node-version: 20
          - angular-version: 19
            node-version: 20
          - angular-version: 20
            node-version: 22

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm ci

      - name: Change package file for versioning
        run: |
          mv package.json package-temp.json
          cp package/v${{ matrix.angular-version }}/package.json ./package.json

      - name: Install Dependencies for Angular ${{ matrix.angular-version }}
        run: |
          npm install

      - name: Build Library
        run: npm run build:lib

      - name: Update version in package.json
        run: |
          VERSION_FILE="./dist/ds-ng-${{ matrix.angular-version }}/package.json"
          sed -i "s/{angularVersion}/${{ matrix.angular-version }}/g" $VERSION_FILE

      - name: Publish to NPM
        run: |
          npm publish ./dist/ds-ng-${{ matrix.angular-version }} --tag a${{ matrix.angular-version }} --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
