name: Publish Multi-version Bamboo

on:
  push:
    branches:
      - develop

jobs:
  build-and-publish-17:
    runs-on: ubuntu-latest
    env:
      ANGULAR_VERSION: 17
      NODE_VERSION: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm ci

      - name: Change package file for versioning
        run: |
          rm package.json
          cp ./package/v${{ env.ANGULAR_VERSION }}/package.json ./package.json

      - name: Install Dependencies for Angular ${{ env.ANGULAR_VERSION }}
        run: |
          npm install

      - name: Build Library
        run: npm run build:lib

      - name: Update version in package.json
        run: |
          VERSION_FILE="./dist/ds-ng-${{ env.ANGULAR_VERSION }}/package.json"
          sed -i "s/{angularVersion}/${{ env.ANGULAR_VERSION }}/g" $VERSION_FILE

      - name: Publish to NPM
        run: |
          npm publish ./dist/ds-ng-${{ env.ANGULAR_VERSION }} --tag a${{ env.ANGULAR_VERSION }} --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  build-and-publish-18:
    runs-on: ubuntu-latest
    env:
      ANGULAR_VERSION: 18
      NODE_VERSION: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm ci

      - name: Change package file for versioning
        run: |
          rm package.json package-temp.json
          cp ./package/v${{ env.ANGULAR_VERSION }}/package.json ./package.json

      - name: Install Dependencies for Angular ${{ env.ANGULAR_VERSION }}
        run: |
          npm install

      - name: Build Library
        run: npm run build:lib

      - name: Update version in package.json
        run: |
          VERSION_FILE="./dist/ds-ng-${{ env.ANGULAR_VERSION }}/package.json"
          sed -i "s/{angularVersion}/${{ env.ANGULAR_VERSION }}/g" $VERSION_FILE

      - name: Publish to NPM
        run: |
          npm publish ./dist/ds-ng-${{ env.ANGULAR_VERSION }} --tag a${{ env.ANGULAR_VERSION }} --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  build-and-publish-19:
    runs-on: ubuntu-latest
    env:
      ANGULAR_VERSION: 19
      NODE_VERSION: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm ci

      - name: Change package file for versioning
        run: |
          rm package.json package-temp.json
          cp ./package/v${{ env.ANGULAR_VERSION }}/package.json ./package.json

      - name: Install Dependencies for Angular ${{ env.ANGULAR_VERSION }}
        run: |
          npm install

      - name: Build Library
        run: npm run build:lib

      - name: Update version in package.json
        run: |
          VERSION_FILE="./dist/ds-ng-${{ env.ANGULAR_VERSION }}/package.json"
          sed -i "s/{angularVersion}/${{ env.ANGULAR_VERSION }}/g" $VERSION_FILE

      - name: Publish to NPM
        run: |
          npm publish ./dist/ds-ng-${{ env.ANGULAR_VERSION }} --tag a${{ env.ANGULAR_VERSION }} --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  build-and-publish-20:
    runs-on: ubuntu-latest
    env:
      ANGULAR_VERSION: 20
      NODE_VERSION: 22

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm ci

      - name: Change package file for versioning
        run: |
          rm package.json package-temp.json
          cp ./package/v${{ env.ANGULAR_VERSION }}/package.json ./package.json

      - name: Install Dependencies for Angular ${{ env.ANGULAR_VERSION }}
        run: |
          npm install

      - name: Build Library
        run: npm run build:lib

      - name: Update version in package.json
        run: |
          VERSION_FILE="./dist/ds-ng-${{ env.ANGULAR_VERSION }}/package.json"
          sed -i "s/{angularVersion}/${{ env.ANGULAR_VERSION }}/g" $VERSION_FILE

      - name: Publish to NPM
        run: |
          npm publish ./dist/ds-ng-${{ env.ANGULAR_VERSION }} --tag a${{ env.ANGULAR_VERSION }} --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
