name: Build & SonarCloud

on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-check:
    name: Build Library
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install Dependencies
        run: npm install

      - name: Build Library
        run: npm run build:lib

  # e2e:
  #   name: E2E Tests (Playwright)
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 24

  #     - name: Install Dependencies
  #       run: npm install

  #     - name: Install Playwright Browsers
  #       run: npx playwright install chromium --with-deps

  #     - name: Run E2E Tests
  #       run: npm run e2e

  #     - name: Upload Playwright Report
  #       uses: actions/upload-artifact@v4
  #       if: always()
  #       with:
  #         name: playwright-report
  #         path: playwright-report/
  #         retention-days: 7

  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Mejor relevancia del análisis

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        with:
          args: >
            -Dsonar.organization=ti-tecnologico-de-monterrey-oficial
            -Dsonar.projectKey=tec-design-system-ng
            -Dsonar.sources=./projects/ds-ng
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.exclusions=**/node_modules/**
            -Dsonar.exclusions=**/*.stories.ts
            -Dsonar.exclusions=**/*.mdx
            -Dsonar.exclusions=**/*.spec.ts
            -Dsonar.test.exclusions=**/*.spec.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Info de PR
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Token Sonar
