name: Build & SonarCloud

on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Mejor relevancia del análisis

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        with:
          args: >
            -Dsonar.organization=ti-tecnologico-de-monterrey-oficial
            -Dsonar.projectKey=tec-design-system-ng
            -Dsonar.sources=./projects/ds-ng
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.exclusions=**/node_modules/**
            -Dsonar.exclusions=**/*.stories.ts
            -Dsonar.test.exclusions=**/*.spec.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Info de PR
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Token Sonar
